### ISSUE TITLE
Automatic time requires manual update?

### ISSUE THREAD

**Issue by ruimarinho** [OpenEVSE/openevse_wifi_gui#22]
Looking at https://github.com/OpenEVSE/openevse_wifi_gui/blob/200ec89f7c3489e5b5fa440e94ebd614ae9d4106/src/view_models/TimeViewModel.js#L107-L111, it seems like the "Automatic" time feature actually requires the `setTime()` function to be called via the UI's `Update` button to trigger the `$S1` message.

I'm a bit confused by this behaviour if what I described is correct. I thought Automatic meant OpenEVSE would updates its RTC automatically via something like (S)NTP.

Could you please clarify this behaviour?

**Comment by ruimarinho** [comment]
Searching for NTP on the OpenEVSE organisation has pointed me to https://github.com/OpenEVSE/ESP32_WiFi_V3.x/pull/56. It seems like my observation is correct and that NTP support was indeed the chosen implementation.

On a side note, the NTP server should be made configurable to avoid requiring internet connectivity (I run a local NTP server on my IoT VLAN).

**Comment by jeremypoulter** [comment]
In this case it is more 'semi-automatic', the time is read from the Browsers' time and sent to the EVSE rather than manually setting the time. NTP support is however available on the ESP32 and include the ability to configure it. all these changes are on the `esp32_mongoose_gui` branch, and also include renaming the automatic option to 'Browser'
